name = "story-library"
compatibility_date = "2026-02-14"
pages_build_output_dir = "app/dist"

[vars]
APP_VERSION = "0.1.0"
CF_AI_EMBED_MODEL = "@cf/baai/bge-base-en-v1.5"

[[d1_databases]]
binding = "STORY_DB"
database_name = "story-library"
database_id = "60a04c35-39c9-410d-8039-4c9330fcc990"
migrations_dir = "db/migrations"

[[r2_buckets]]
binding = "STORY_BUCKET"
bucket_name = "story-library"

[[vectorize]]
binding = "STORY_VECTORS"
index_name = "story-library-vectors"

[ai]
binding = "AI"
